FROM registry.redhat.io/jboss-eap-7/eap74-openjdk8-openshift-rhel7:7.4.7-2.1666732053

USER root
WORKDIR /home/jboss

RUN microdnf install unzip

COPY /ear-remote/target/kitchensink-ear-remote.ear /opt/eap/standalone/deployments/kitchensink-ear-remote.ear
COPY /ear/target/kitchensink-ear.ear /opt/eap/standalone/deployments/kitchensink-ear.ear

COPY /opt/eap/standalone/configuration/

USER 185

# Specify the working directory
WORKDIR /home/jboss

CMD ["/opt/eap/bin/standalone.sh","-b","0.0.0.0"]