FROM registry.access.redhat.com/ubi8/openjdk-8:1.14-5.1666624658

USER root
WORKDIR /home/jboss

RUN microdnf install unzip

COPY jboss-eap-7.4-monolith.zip /home/jboss/jboss-eap-7.4-monolith.zip

USER jboss

RUN unzip jboss-eap-7.4-monolith.zip

WORKDIR /home/jboss/jboss-eap-7.4-monolith

EXPOSE 8080
CMD ["/home/jboss/jboss-eap-7.4-monolith/bin/standalone.sh","-b","0.0.0.0"]